version: 2.1
jobs:
  build:
    docker:
      - image: node:18.12
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test for the application
          command: npm run test:unit
      - run:
          name: Build application for production
          command: npm run build 
      - run:
          name: Install git-ftp
          command: apt-get install git-ftp
      - run:
          name: Deploy using git-ftp
          command: git ftp push --syncroot ./dist --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_SERVER
workflows:
  build:
    jobs:
      - build